### ISSUE TITLE
OAuthError: User is not assigned to the client application.

### ISSUE THREAD

**Issue by drldavis** [okta/samples-js-vue#118]
I followed the README instructions for the vue-sample exactly but I'm getting this error whenever I hit the login button.

My environment variables: 
`ISSUER=dev-98975133.okta.com/oauth2/default
CLIENT_ID=0oao9k9jr1vQz655d6`

Not sure what this error is telling me.

**Comment by mraible** [comment]
You need to assign your user or the Everyone group to your app.

**Comment by drldavis** [comment]
Oh that makes sense. I didn’t see this step in the README or the getting started docs. Did I just miss something?

**Comment by mraible** [comment]
No, you didn't miss anything. It used to happen by default, that's why it's not documented. We're restoring the defaults soon.

**Comment by drldavis** [comment]
Is there another missing step to get logout to work? Clicking logout gives me a CORS error. `No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by mraible** [comment]
Yes, you have to add your app's address as a trusted origin in Security > API > Trusted Origins.

**Comment by drldavis** [comment]
Oh okay thanks. Why would logout require CORS but login not?

**Comment by mraible** [comment]
Because login does a redirect while logout does an XHR request.
