### ISSUE TITLE
🔴unsupported_response_type returned running custom sign up page example

### ISSUE THREAD

**Issue by webdevbrian** [okta/samples-js-vue#37]
Using the custom sign up page example, this error is returned:

```
The response type is not supported by the authorization server. Configured response types: [id_token].
```

**Comment by swiftone** [comment]
Are you using an application configured as SWA or one otherwise configured for PKCE?

**Comment by swiftone** [comment]
Closing due to lack of response.  If this continues to be an issue, feel free to reopen.
