### ISSUE TITLE
Okta wiget testing using jest in vue

### ISSUE THREAD

**Issue by raghuvarbisht** [okta/samples-js-vue#56]
Hi ,
How i can test okta widget implemenation in vue project?

**Comment by swiftone** [comment]
@raghuvarbisht - Happy to help.  Can you clarify what you are looking to try?  Manual testing or automated testing?

The "Custom login" from this sample should allow you to use the widget with this Vue SDK.  ( https://github.com/okta/samples-js-vue/tree/master/custom-login )

**Comment by raghuvarbisht** [comment]
Hi,
I am using jest for unit testing in my @vue/cli project and want to write unit test using jest  for okta widget authentication.Can you please help how we can write uni test for OKTA widget using jest in vue?

**Comment by swiftone** [comment]
At the unit testing level you do not want to test the widget itself, you should test the parameters you pass in to the widget and the values your code would receive.

**Comment by swiftone** [comment]
Closing this issue as stale.  If a code/feature problem still exists, feel free to reopen or create a new issue with additional details.
